export enum AssetClassType{
    NON_US_GOVERNMENT_DEBT = 'Non-US Government Debt',
    US_TREASURY_DEBT = 'US Treasury Debt',
    US_AGENCY_BONDS = 'US Agency Bonds',
    MUNICIPAL_BONDS = 'Municipal Bonds',
    CORPORATE_BONDS = 'Corporate Bonds',
    PUBLIC_EQUITY = 'Public Equity',
    PRIVATE_EQUITY = 'Private Equity',
    PRIVATE_FUNDS = 'Private Funds',
    PRIVATE_CREDIT = 'Private Credit',
    STRUCTURED_CREDIT = 'Structured Credit',
    DIGITAL_ASSET_SECURITY = 'Digital Asset Security',
    CRYPTOCURRENCIES = 'Cryptocurrencies',
    STABLECOINS = 'Stablecoins',
    REAL_ESTATE = 'Real Estate',
    PHYSICAL_ITEMS = 'Physical Items',
    MORTGAGES = 'Mortgages',
    DERIVATIVES = 'Derivatives',
    BANK_DEPOSITS = 'Bank Deposits',
    MONEY_MARKET = 'Money Market',
    COMMODITIES = 'Commodities'
}
