export enum AssociatedNetwork {
    ETHEREUM_BINANCE_SMART_CHAIN_BNB_CHAIN = 'Ethereum, Binance Smart Chain (BNB Chain)',
    SOLANA = 'Solana',
    AVALANCHE_C_CHAIN = 'Avalanche (C-Chain)',
    CARDANO = 'Cardano',
    TRON = 'Tron',
    FANTOM = 'Fantom',
    POLYGON_POS_CHAIN = 'Polygon (PoS Chain)',
    POLKADOT = 'Polkadot',
    ALGORAND = 'Algorand',
    NEAR = 'NEAR',
    COSMOS = 'Cosmos',
    TEZOS = 'Tezos',
    HARMONY = 'Harmony',
    ARBITRUM = 'Arbitrum',
    OPTIMISM = 'Optimism',
    ZKSYNC = 'zkSync',
    STARKNET = 'StarkNet',
    LOOPRING = 'Loopring',
    POLYGON_HERMEZ_ZKEVM = 'Polygon Hermez (zkEVM)',
    IMMUTABLE_X = 'Immutable X',
    AZTEC = 'Aztec',
    METIS = 'Metis',
    BOBA_NETWORK = 'Boba Network',
    FUEL = 'Fuel',
    SHARDEUM = 'Shardeum',
}

