export enum FifthCharacterIdentifier {
    A = "A Class A",
    B = "B Class B",
    D = "D New",
    E = "E Delinquent in required SEC filings",
    F = "F Foreign issues, except ADRs",
    G_H_I = "G, H & I Additional warrants or preferred",
    J = "J Voting",
    K = "K Nonvoting",
    L = "L Miscellaneous situations, such as stubs, depositary receipts, second units, or additional warrants or preferred",
    M = "M Fourth preferred, same issuer",
    N = "N Third preferred, same issuer",
    O = "O Second preferred, same issuer",
    P = "P First preferred issue",
    Q = "Q Bankruptcy - involved in bankruptcy proceedings",
    R = "R Rights",
    S = "S Shares of beneficial interest",
    U = "U Units",
    V = "V When-issued and when-distributed",
    W = "W Warrants",
    Y = "Y ADR (American Depositary Receipts)",
    Z = "Z Miscellaneous situations, such as stubs, depositary receipts, limited partnership units, or additional warrants or units"
}
