export enum SecurityType {
    AMERICAN_DEPOSITARY_RECEIPTS_SPONSORED = "American Depositary Receipts - Sponsored",
    AMERICAN_DEPOSITARY_RECEIPTS_UNSPONSORED = "American Depositary Receipts - Unsponsored",
    AMERICAN_DEPOSITARY_SHARES_UNSPONSORED = "American Depositary Shares - Unsponsored",
    TRUST_CERTIFICATES = "Trust Certificates",
    COMMON_SHARES = "Common Shares",
    COMMON_STOCK = "Common Stock",
    DEPOSITARY_RECEIPTS = "Depositary Receipts",
    DEPOSITARY_SHARES = "Depositary Shares",
    FOREIGH_EXCHANGE_TRADED_FUNDS = "Foreign Exchange Traded Fund",
    GLOBAL_DEPOSITARY_RECEIPTS = "Global Depositary Receipts - Sponsored",
    GLOBAL_DEPOSITARY_SHARES_SPONSORED = "Global Depositary Shares - Sponsored",
    DPP_LIMITED_PARTNERSHIP = "DPP/Limited Partnership",
    ORDINARY_SHARES = "Ordinary Shares",
    OTHER = "Other",
    PREFERENCE_SHARES = "Preference Shares",
    PREFERRED_STOCK = "Preferred Stock",
    REIT = "REIT",
    RIGHTS = "Rights",
    SHARES_OF_BENEFICIAL_INTEREST = "Shares of Beneficial Interest",
    UNIT = "Unit",
    WARRANT = "Warrant",
    GLOBAL_DEPOSITARY_RECEIPTS_UNSPONSORED = "Global Depositary Receipts - Unsponsored",
    EXCHANGE_TRADED_FUND = "Exchange Traded Fund",
    AMERICAN_DEPOSITARY_SHARES_SPONSORED = "American Depositary Shares – Sponsored",
}
