import BaseService from "@/services/base/base-service";
import apiWebBackendService from "@/services/web-backend/web-backend-api-service";
import {IIndicator} from "@/interfaces/i-indicator";
import {IMarketStatistics} from "@/interfaces/i-market-statistics";

class StatisticsService extends BaseService {

    private PATH = 'statistics/';

    constructor() {
        super();
    }

    public async getIndicators(): Promise<Array<IIndicator>> {
        return (await apiWebBackendService.get<IResponse<Array<IIndicator>>>(`${this.PATH}indicators/`, {}, this.getUserAccessToken())).data;
    }

    public async getMarketData(): Promise<Array<IMarketStatistics>> {
        // return (await apiWebBackendService.get<IResponse<Array<IMarketStatistics>>>(`${this.PATH}market/`, {}, this.getUserAccessToken())).data;

        return new Promise(resolve => {
            resolve([
                {
                    "symbol": "TEST",
                    "symbol_name": "TEST",
                    "last_price": "20.02",
                    "price_changed": "1.55",
                    "percentage_changed": "2.99",
                    "company_profile": {
                        "id": 6,
                        "logo": "/media/company_profile_logo/logo.jpg",
                        "security_name": "TEST",
                        "company_name": "Test Company LTD.",
                        "business_description": "",
                        "street_address_1": "1",
                        "street_address_2": "",
                        "city": "",
                        "state": "",
                        "zip_code": "",
                        "country": "",
                        "phone": "",
                        "web_address": "",
                        "sic_industry_classification": "",
                        "incorporation_information": "",
                        "number_of_employees": '1',
                        "company_officers_and_contacts": [],
                        "board_of_directors": [],
                        "product_and_services": "",
                        "company_facilities": "",
                        "transfer_agent": "",
                        "accounting_auditing_firm": "",
                        "investor_relations_marketing_communications": "",
                        "securities_counsel": "",
                        "us_reporting": "",
                        "edgar_cik": "",
                        "is_approved": true,
                        "status": "approved",
                        "updated_at": "2023-11-03T18:25:33.539997Z",
                        "symbol": '1',
                        "approved_date_time": "2023-11-03T18:25:33.539997Z",
                        "logo_tmp": "",
                        "approved_by": "1"
                    }
                },
                {
                    "symbol": "TEST2",
                    "symbol_name": "TEST2",
                    "last_price": "16.54",
                    "price_changed": "-9.22",
                    "percentage_changed": "-0.33",
                    "company_profile": {
                        "id": 6,
                        "logo": "/media/company_profile_logo/logo.jpg",
                        "security_name": "TEST",
                        "company_name": "Test Company LTD.",
                        "business_description": "",
                        "street_address_1": "1",
                        "street_address_2": "",
                        "city": "",
                        "state": "",
                        "zip_code": "",
                        "country": "",
                        "phone": "",
                        "web_address": "",
                        "sic_industry_classification": "",
                        "incorporation_information": "",
                        "number_of_employees": '1',
                        "company_officers_and_contacts": [],
                        "board_of_directors": [],
                        "product_and_services": "",
                        "company_facilities": "",
                        "transfer_agent": "",
                        "accounting_auditing_firm": "",
                        "investor_relations_marketing_communications": "",
                        "securities_counsel": "",
                        "us_reporting": "",
                        "edgar_cik": "",
                        "is_approved": true,
                        "status": "approved",
                        "updated_at": "2023-11-03T18:25:33.539997Z",
                        "symbol": '1',
                        "approved_date_time": "2023-11-03T18:25:33.539997Z",
                        "logo_tmp": "",
                        "approved_by": "1"
                    }
                },
                {
                    "symbol": "TEST3",
                    "symbol_name": "TEST",
                    "last_price": "20.02",
                    "price_changed": "0.0",
                    "percentage_changed": "0.0",
                    "company_profile": {
                        "id": 6,
                        "logo": "/media/company_profile_logo/logo.jpg",
                        "security_name": "TEST",
                        "company_name": "Test Company LTD.",
                        "business_description": "",
                        "street_address_1": "1",
                        "street_address_2": "",
                        "city": "",
                        "state": "",
                        "zip_code": "",
                        "country": "",
                        "phone": "",
                        "web_address": "",
                        "sic_industry_classification": "",
                        "incorporation_information": "",
                        "number_of_employees": '1',
                        "company_officers_and_contacts": [],
                        "board_of_directors": [],
                        "product_and_services": "",
                        "company_facilities": "",
                        "transfer_agent": "",
                        "accounting_auditing_firm": "",
                        "investor_relations_marketing_communications": "",
                        "securities_counsel": "",
                        "us_reporting": "",
                        "edgar_cik": "",
                        "is_approved": true,
                        "status": "approved",
                        "updated_at": "2023-11-03T18:25:33.539997Z",
                        "symbol": '1',
                        "approved_date_time": "2023-11-03T18:25:33.539997Z",
                        "logo_tmp": "",
                        "approved_by": "1"
                    }
                },
                {
                    "symbol": "TEST4",
                    "symbol_name": "TEST2",
                    "last_price": "16.54",
                    "price_changed": "9.22",
                    "percentage_changed": "0.33",
                    "company_profile": {
                        "id": 6,
                        "logo": "/media/company_profile_logo/logo.jpg",
                        "security_name": "TEST",
                        "company_name": "Test Company LTD.",
                        "business_description": "",
                        "street_address_1": "1",
                        "street_address_2": "",
                        "city": "",
                        "state": "",
                        "zip_code": "",
                        "country": "",
                        "phone": "",
                        "web_address": "",
                        "sic_industry_classification": "",
                        "incorporation_information": "",
                        "number_of_employees": '1',
                        "company_officers_and_contacts": [],
                        "board_of_directors": [],
                        "product_and_services": "",
                        "company_facilities": "",
                        "transfer_agent": "",
                        "accounting_auditing_firm": "",
                        "investor_relations_marketing_communications": "",
                        "securities_counsel": "",
                        "us_reporting": "",
                        "edgar_cik": "",
                        "is_approved": true,
                        "status": "approved",
                        "updated_at": "2023-11-03T18:25:33.539997Z",
                        "symbol": '1',
                        "approved_date_time": "2023-11-03T18:25:33.539997Z",
                        "logo_tmp": "",
                        "approved_by": "1"
                    }
                },
                {
                    "symbol": "TEST5",
                    "symbol_name": "TEST",
                    "last_price": "20.02",
                    "price_changed": "1.55",
                    "percentage_changed": "2.99",
                    "company_profile": {
                        "id": 6,
                        "logo": "/media/company_profile_logo/logo.jpg",
                        "security_name": "TEST",
                        "company_name": "Test Company LTD.",
                        "business_description": "",
                        "street_address_1": "1",
                        "street_address_2": "",
                        "city": "",
                        "state": "",
                        "zip_code": "",
                        "country": "",
                        "phone": "",
                        "web_address": "",
                        "sic_industry_classification": "",
                        "incorporation_information": "",
                        "number_of_employees": '1',
                        "company_officers_and_contacts": [],
                        "board_of_directors": [],
                        "product_and_services": "",
                        "company_facilities": "",
                        "transfer_agent": "",
                        "accounting_auditing_firm": "",
                        "investor_relations_marketing_communications": "",
                        "securities_counsel": "",
                        "us_reporting": "",
                        "edgar_cik": "",
                        "is_approved": true,
                        "status": "approved",
                        "updated_at": "2023-11-03T18:25:33.539997Z",
                        "symbol": '1',
                        "approved_date_time": "2023-11-03T18:25:33.539997Z",
                        "logo_tmp": "",
                        "approved_by": "1"
                    }
                },
                {
                    "symbol": "TEST6",
                    "symbol_name": "TEST2",
                    "last_price": "16.54",
                    "price_changed": "9.22",
                    "percentage_changed": "0.33",
                    "company_profile": {
                        "id": 6,
                        "logo": "/media/company_profile_logo/logo.jpg",
                        "security_name": "TEST",
                        "company_name": "Test Company LTD.",
                        "business_description": "",
                        "street_address_1": "1",
                        "street_address_2": "",
                        "city": "",
                        "state": "",
                        "zip_code": "",
                        "country": "",
                        "phone": "",
                        "web_address": "",
                        "sic_industry_classification": "",
                        "incorporation_information": "",
                        "number_of_employees": '1',
                        "company_officers_and_contacts": [],
                        "board_of_directors": [],
                        "product_and_services": "",
                        "company_facilities": "",
                        "transfer_agent": "",
                        "accounting_auditing_firm": "",
                        "investor_relations_marketing_communications": "",
                        "securities_counsel": "",
                        "us_reporting": "",
                        "edgar_cik": "",
                        "is_approved": true,
                        "status": "approved",
                        "updated_at": "2023-11-03T18:25:33.539997Z",
                        "symbol": '1',
                        "approved_date_time": "2023-11-03T18:25:33.539997Z",
                        "logo_tmp": "",
                        "approved_by": "1"
                    }
                },
                {
                    "symbol": "TEST7",
                    "symbol_name": "TEST",
                    "last_price": "20.02",
                    "price_changed": "1.55",
                    "percentage_changed": "2.99",
                    "company_profile": {
                        "id": 6,
                        "logo": "/media/company_profile_logo/logo.jpg",
                        "security_name": "TEST",
                        "company_name": "Test Company LTD.",
                        "business_description": "",
                        "street_address_1": "1",
                        "street_address_2": "",
                        "city": "",
                        "state": "",
                        "zip_code": "",
                        "country": "",
                        "phone": "",
                        "web_address": "",
                        "sic_industry_classification": "",
                        "incorporation_information": "",
                        "number_of_employees": '1',
                        "company_officers_and_contacts": [],
                        "board_of_directors": [],
                        "product_and_services": "",
                        "company_facilities": "",
                        "transfer_agent": "",
                        "accounting_auditing_firm": "",
                        "investor_relations_marketing_communications": "",
                        "securities_counsel": "",
                        "us_reporting": "",
                        "edgar_cik": "",
                        "is_approved": true,
                        "status": "approved",
                        "updated_at": "2023-11-03T18:25:33.539997Z",
                        "symbol": '1',
                        "approved_date_time": "2023-11-03T18:25:33.539997Z",
                        "logo_tmp": "",
                        "approved_by": "1"
                    }
                },
                {
                    "symbol": "TEST8",
                    "symbol_name": "TEST2",
                    "last_price": "16.54",
                    "price_changed": "9.22",
                    "percentage_changed": "0.33",
                    "company_profile": {
                        "id": 6,
                        "logo": "/media/company_profile_logo/logo.jpg",
                        "security_name": "TEST",
                        "company_name": "Test Company LTD.",
                        "business_description": "",
                        "street_address_1": "1",
                        "street_address_2": "",
                        "city": "",
                        "state": "",
                        "zip_code": "",
                        "country": "",
                        "phone": "",
                        "web_address": "",
                        "sic_industry_classification": "",
                        "incorporation_information": "",
                        "number_of_employees": '1',
                        "company_officers_and_contacts": [],
                        "board_of_directors": [],
                        "product_and_services": "",
                        "company_facilities": "",
                        "transfer_agent": "",
                        "accounting_auditing_firm": "",
                        "investor_relations_marketing_communications": "",
                        "securities_counsel": "",
                        "us_reporting": "",
                        "edgar_cik": "",
                        "is_approved": true,
                        "status": "approved",
                        "updated_at": "2023-11-03T18:25:33.539997Z",
                        "symbol": '1',
                        "approved_date_time": "2023-11-03T18:25:33.539997Z",
                        "logo_tmp": "",
                        "approved_by": "1"
                    }
                },
                {
                    "symbol": "TEST9",
                    "symbol_name": "TEST",
                    "last_price": "20.02",
                    "price_changed": "1.55",
                    "percentage_changed": "2.99",
                    "company_profile": {
                        "id": 6,
                        "logo": "/media/company_profile_logo/logo.jpg",
                        "security_name": "TEST",
                        "company_name": "Test Company LTD.",
                        "business_description": "",
                        "street_address_1": "1",
                        "street_address_2": "",
                        "city": "",
                        "state": "",
                        "zip_code": "",
                        "country": "",
                        "phone": "",
                        "web_address": "",
                        "sic_industry_classification": "",
                        "incorporation_information": "",
                        "number_of_employees": '1',
                        "company_officers_and_contacts": [],
                        "board_of_directors": [],
                        "product_and_services": "",
                        "company_facilities": "",
                        "transfer_agent": "",
                        "accounting_auditing_firm": "",
                        "investor_relations_marketing_communications": "",
                        "securities_counsel": "",
                        "us_reporting": "",
                        "edgar_cik": "",
                        "is_approved": true,
                        "status": "approved",
                        "updated_at": "2023-11-03T18:25:33.539997Z",
                        "symbol": '1',
                        "approved_date_time": "2023-11-03T18:25:33.539997Z",
                        "logo_tmp": "",
                        "approved_by": "1"
                    }
                },
                {
                    "symbol": "TEST10",
                    "symbol_name": "TEST2",
                    "last_price": "16.54",
                    "price_changed": "9.22",
                    "percentage_changed": "0.33",
                    "company_profile": {
                        "id": 6,
                        "logo": "/media/company_profile_logo/logo.jpg",
                        "security_name": "TEST",
                        "company_name": "Test Company LTD.",
                        "business_description": "",
                        "street_address_1": "1",
                        "street_address_2": "",
                        "city": "",
                        "state": "",
                        "zip_code": "",
                        "country": "",
                        "phone": "",
                        "web_address": "",
                        "sic_industry_classification": "",
                        "incorporation_information": "",
                        "number_of_employees": '1',
                        "company_officers_and_contacts": [],
                        "board_of_directors": [],
                        "product_and_services": "",
                        "company_facilities": "",
                        "transfer_agent": "",
                        "accounting_auditing_firm": "",
                        "investor_relations_marketing_communications": "",
                        "securities_counsel": "",
                        "us_reporting": "",
                        "edgar_cik": "",
                        "is_approved": true,
                        "status": "approved",
                        "updated_at": "2023-11-03T18:25:33.539997Z",
                        "symbol": '1',
                        "approved_date_time": "2023-11-03T18:25:33.539997Z",
                        "logo_tmp": "",
                        "approved_by": "1"
                    }
                },
            ])
        })
    }

}

const symbolService = new StatisticsService();

export default symbolService;

